In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from sklearn import linear_model

In [2]:
ironkaggle = pd.read_csv('sales.csv')

In [22]:
ironkaggle.dtypes

Unnamed: 0                      int64
store_ID                        int64
day_of_week                     int64
date                   datetime64[ns]
nb_customers_on_day             int64
open                            int64
promotion                       int64
state_holiday                   int64
school_holiday                  int64
sales                           int64
dtype: object

In [11]:
ironkaggle.date = pd.to_datetime(ironkaggle.date)

In [15]:
ironkaggle.state_holiday.unique()

array(['0', 'a', 'c', 'b'], dtype=object)

In [18]:
ironkaggle.sort_values(by=['state_holiday', 'date'])

Unnamed: 0  store_ID  day_of_week       date  nb_customers_on_day  \
837         687618        12            3 2013-01-02                  786   
939         604171       950            3 2013-01-02                  569   
1109        259453       706            3 2013-01-02                  499   
1325        424298       693            3 2013-01-02                  382   
2263        338396       811            3 2013-01-02                  786   
...            ...       ...          ...        ...                  ...   
633979      315567       343            5 2014-12-26                    0   
636046      131416       253            5 2014-12-26                    0   
636765      128810       176            5 2014-12-26                    0   
636870      434580       401            5 2014-12-26                    0   
640454       26981       615            5 2014-12-26                    0   

        open  promotion state_holiday  school_holiday  sales  
837        1          0             0               1   5029  
939        1          0             0               1   5268  
1109       1          0             0               1   5072  
1325       1          0             0               1   4945  
2263       1          0             0               1   4607  
...      ...        ...           ...             ...    ...  
633979     0          0             c               1      0  
636046     0          0             c               1      0  
636765     0          0             c               1      0  
636870     0          0             c               1      0  
640454     0          0             c               1      0  

[640840 rows x 10 columns]

In [19]:
ironkaggle['state_holiday'] = ironkaggle['state_holiday'].map({'0': 0, 'a': 1, 'b': 2, 'c': 3})

In [23]:
ironkaggle = ironkaggle.rename(columns={'Unnamed: 0': 'index'})

In [73]:
ironkaggle['year'] = ironkaggle['date'].dt.year
ironkaggle['month'] = ironkaggle['date'].dt.month
ironkaggle['day'] = ironkaggle['date'].dt.day

In [170]:
features = ironkaggle.drop(['sales', 'date', 'index'], axis=1)
labels = ironkaggle['sales']

In [171]:
display(features)
display(labels)

store_ID  day_of_week  nb_customers_on_day  open  promotion  \
0            366            4                  517     1          0   
1            394            6                  694     1          0   
2            807            4                  970     1          1   
3            802            2                  473     1          1   
4            726            4                 1068     1          1   
...          ...          ...                  ...   ...        ...   
640835       409            6                  483     1          0   
640836        97            1                  987     1          1   
640837       987            1                  925     1          0   
640838      1084            4                  725     1          0   
640839       695            7                    0     0          0   

        state_holiday  school_holiday  year  month  day  
0                   0               0  2013      4   18  
1                   0               0  2015      4   11  
2                   0               0  2013      8   29  
3                   0               0  2013      5   28  
4                   0               0  2013     10   10  
...               ...             ...   ...    ...  ...  
640835              0               0  2013     10   26  
640836              0               0  2014      4   14  
640837              0               0  2014      7    7  
640838              0               0  2014      6   12  
640839              0               0  2015      5    3  

[640840 rows x 10 columns]

0          4422
1          8297
2          9729
3          6513
4         10882
          ...  
640835     4553
640836    12307
640837     6800
640838     5344
640839        0
Name: sales, Length: 640840, dtype: int64

In [172]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, labels, random_state=0)

In [173]:
model = linear_model.LinearRegression()
result = model.fit(X_train, y_train)

In [174]:
y_pred = model.predict(X_test)

In [175]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [135]:
print(mse)
print(r2)

2559076.463683519
0.7322364003468891


In [176]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor

In [177]:
knn_model = KNeighborsRegressor(n_neighbors=9)

In [178]:
knn_model.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=9)

In [179]:
y_pred = knn_model.predict(X_test)
y_pred

array([3834.55555556, 5177.88888889, 6879.33333333, ..., 2745.77777778,
       4614.33333333, 8447.44444444])

In [180]:
np.array(y_test)

array([4025, 5538, 5579, ..., 2680, 5889, 8864], dtype=int64)

In [181]:
mse = mean_squared_error(y_test, y_pred)

print(f'Mean Squared Error: {mse}')

r2 = r2_score(y_val, y_pred_val)

print(f'R2 Score: {r2}')

Mean Squared Error: 1729514.2860380008
R2 Score: 0.6692131783586244


In [183]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, random_state=42, test_size=0.2)
X_train_2, X_val, y_train_2, y_val = train_test_split(X_train, y_train, random_state=42, test_size=0.25)

In [184]:
print('Train set %', len(X_train_2) * 100 / len(features))
print('Validation set %', len(X_val) * 100 / len(features))
print('Test set %', len(X_test) * 100 / len(features))

Train set % 60.0
Validation set % 20.0
Test set % 20.0


In [185]:
knn_model = KNeighborsRegressor(n_neighbors=2)
knn_model.fit(X_train_2, y_train_2)
y_pred_val = knn_model.predict(X_val)
y_pred_train = knn_model.predict(X_train_2)

In [162]:
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor

In [187]:
# Bagging w/ pasting
bagging_reg = BaggingRegressor(
    DecisionTreeRegressor(max_depth=3), # depth 3 to force tree to be "weak"
    n_estimators=10, # 10 trees
    max_samples=100, # we limit each weaker tree to 100 datapoints
    bootstrap=False, # by default, the bagging regressor does bootstrapping
    random_state=1) # fixing random state because I want my examples to work and to look smart

bagging_reg.fit(X_train, y_train)
print('Train score:', bagging_reg.score(X_train, y_train))
print('Test score:', bagging_reg.score(X_test, y_test))

Train score: 0.836092947981105
Test score: 0.8355149798386883


In [188]:
# Bagging w/ bootstrapping
bagging_reg = BaggingRegressor(
    DecisionTreeRegressor(max_depth=3), # depth 3 to force tree to be "weak"
    n_estimators=10, # 10 trees
    max_samples=100, # we limit each weaker tree to 100 datapoints
    bootstrap=True,  # by default, the bagging regressor does bootstrapping
    random_state=1) # fixing random state because I want my examples to work and to look smart

bagging_reg.fit(X_train, y_train)
print('Train score:', bagging_reg.score(X_train, y_train))
print('Test score:', bagging_reg.score(X_test, y_test))

Train score: 0.836092947981105
Test score: 0.8355149798386883


In [189]:
from sklearn.ensemble import RandomForestRegressor

forest = RandomForestRegressor(n_estimators=10, # same 10 trees
                               #max_samples=100,
                               #max_features=0.6,
                               max_depth=3, # depth 3 to force tree to be "weak"
                               random_state=1) # fixing rand because I'm insecure and afraid you will judge me if I get a bad random selection that does not prove my point
forest.fit(X_train, y_train)
print('Train score:', forest.score(X_train, y_train))
print('Test score:', forest.score(X_test, y_test))

Train score: 0.8171083649864864
Test score: 0.8175704334763318


In [190]:
from sklearn.ensemble import AdaBoostRegressor

ada_reg = AdaBoostRegressor(DecisionTreeRegressor(max_depth=5), # you can overfit a bit because you compensate afterwards
                            n_estimators=10, # same 10 trees. You usually use faaaar more estimators
                            random_state=1 # once a coward, always a coward
                            )
ada_reg.fit(X_train, y_train)
print('Train score:', ada_reg.score(X_train, y_train))
print('Test score:', ada_reg.score(X_test, y_test))

Train score: 0.8643912424599511
Test score: 0.8625634169346146


In [191]:
ada_reg = AdaBoostRegressor(DecisionTreeRegressor(max_depth=5),
                            n_estimators=50, # that's more like it
                            random_state=1 # once a coward, always a coward
                            )
ada_reg.fit(X_train, y_train)
print('Train score:', ada_reg.score(X_train, y_train))
print('Test score:', ada_reg.score(X_test, y_test))

Train score: 0.8046057181295626
Test score: 0.802540129608925


In [192]:
from sklearn.ensemble import GradientBoostingRegressor

gb_reg = GradientBoostingRegressor(max_depth=5, #gradient boosting always works with trees, no need to call the tree regressor
                                   n_estimators=50,
                                   random_state=1 # tastes like chicken
                                   )
gb_reg.fit(X_train, y_train)
gb_reg.score(X_test,y_test)

0.8936074668593242

In [194]:
!pip install xgboost

   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/99.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/99.8 MB 656.4 kB/s eta 0:02:32
   ---------------------------------------- 0.2/99.8 MB 1.5 MB/s eta 0:01:09
   ---------------------------------------- 0.5/99.8 MB 2.5 MB/s eta 0:00:40
   ---------------------------------------- 0.7/99.8 MB 3.1 MB/s eta 0:00:33
   ---------------------------------------- 1.0/99.8 MB 3.4 MB/s eta 0:00:29
    --------------------------------------- 1.3/99.8 MB 3.9 MB/s eta 0:00:26
    --------------------------------------- 1.5/99.8 MB 3.9 MB/s eta 0:00:25
    --------------------------------------- 1.7/99.8 MB 4.1 MB/s eta 0:00:24
    --------------------------------------- 2.0/99.8 MB 4.4 MB/s eta 0:00:23
    --------------------------------------- 2.1/99.8 MB 4.3 MB/s eta 0:00:23
    --------------

In [219]:
import xgboost

xgb_reg = xgboost.XGBRegressor(max_depth=5)
xgb_reg.fit(features, labels)
xgb_reg.score(features, labels)

0.9283681714721873

In [214]:
type(pickle.dump)

builtin_function_or_method

In [198]:
# Applying an example of cross validation
from sklearn.model_selection import cross_validate

# Initialize model and cross validate with 10 folds
results = cross_validate(xgb_reg, features, labels, cv=10)
print(results.keys())

dict_keys(['fit_time', 'score_time', 'test_score'])


In [199]:
results['test_score']

array([0.92599446, 0.9284216 , 0.9289145 , 0.92788547, 0.92752974,
       0.92642159, 0.92852888, 0.92545544, 0.92667954, 0.92507905])

In [200]:
results['test_score'].mean()

0.9270910265822586

In [ ]:
xgb_reg = xgboost.XGBRegressor(max_depth=5)
xgb_reg.fit(X_train, y_train)
xgb_reg.score(X_test,y_test)

In [220]:
xgb_reg.save_model('xgb_model.json')

In [221]:
xgb_reg.load_model('xgb_model.json')